export const destinations = [
  {
    id: "1",
    name: "Labuan Bajo",
    category: "pantai",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTcgN1MuBgUyTglS-BypFTan_tOu7L5oFfHIQ&s",
    description: "Destinasi terkenal di Flores dengan pemandangan laut dan pulau-pulau kecil.",
  },
  {
    id: "2",
    name: "Danau Kelimutu",
    category: "gunung",
    image: "https://www.nttonlinenow.com/new-2016/wp-content/uploads/2016/08/danaukelimutu-e1517494195406.jpg",
    description: "Danau tiga warna yang terkenal dan menakjubkan.",
  },
  {
    id: "3",
    name: "Wae Rebo",
    category: "budaya",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSDH-C_5ym9s8cAkyU9SLUgSH1w00OEVgO8Dw&s",
    description: "Desa tradisional yang berada di atas gunung dengan rumah adat unik.",
  },
  {
    id: "4",
    name: "Pantai Koka",
    category: "pantai",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3jS9hvS5z3TzYtsoGvTibBUca-ZQJmqq24g&s",
    description: "Pantai pasir putih dengan dua teluk yang menawan.",
  },
  {
    id: "5",
    name: "Gunung Inerie",
    category: "gunung",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSywmAZV2OVTBkSuN7UKybuOZ9uDBnsYTBk5A&s",
    description: "Gunung berapi yang menjulang megah di Flores bagian barat.",
  },
  {
    id: "6",
    name: "Bena Village",
    category: "budaya",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSokHZ4JURCI_bwAEa74FZVr4cerwMVKPuqGQ&s",
    description: "Kampung adat megalitik dengan budaya yang masih terjaga kuat.",
  },
  {
    id: "7",
    name: "Pantai Nembrala",
    category: "pantai",
    image: "https://static.promediateknologi.id/crop/0x1:1080x741/0x0/webp/photo/p2/74/2024/11/16/ClipDownApp_323307471_1639456529836110_6109050412457668664_n-2371348810.jpg",
    description: "Pantai dengan ombak besar, populer untuk berselancar.",
  },
  {
    id: "8",
    name: "Pantai Batu Biru",
    category: "pantai",
    image: "https://static.promediateknologi.id/crop/0x0:0x0/0x0/webp/photo/p2/178/2024/01/15/6d6deeee-935c-477d-a763-9903def5d02f-1-3740728167.jpg",
    description: "Pantai unik dengan bebatuan biru alami yang eksotis.",
  },
  {
    id: "9",
    name: "Gunung Egon",
    category: "gunung",
    image: "https://cdn1-production-images-kly.akamaized.net/6pmEu2miPjryhQnNJvSlLDg4yks=/1200x900/smart/filters:quality(75):strip_icc():format(webp)/kly-media-production/medias/4689158/original/069550600_1702803094-WhatsApp_Image_2023-12-17_at_15.50.34.jpeg",
    description: "Gunung aktif dengan pemandangan kawah yang dramatis.",
  },
  {
    id: "10",
    name: "Gunung Lewotobi",
    category: "gunung",
    image: "https://cdn.rri.co.id/berita/Pusat_Pemberitaan/o/1725933842278-IMG-20240910-WA0002/a77qibj2jy9n7rf.jpeg",
    description: "Pasangan gunung kembar dengan lanskap yang memesona.",
  },
  {
    id: "11",
    name: "Kampung Todo",
    category: "budaya",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTzuwptsZd9UEr21DAChGZKZp8HjpeCQU2LMA&s",
    description: "Kampung adat tua dengan struktur batu kuno dan sejarah kerajaan Manggarai.",
  },
  {
    id: "12",
    name: "Kampung Wogo",
    category: "budaya",
    image: "https://asset.kompas.com/crops/Qh5T2xxmhHUZygBs3t3TYhrasIA=/0x0:0x0/1200x800/data/photo/2022/09/18/6326e9a63d92c.jpg",
    description: "Desa adat dengan rumah panggung khas dan kehidupan masyarakat yang tradisional.",
  },
];

export const categories = [
  { key: "all", label: "Semua" },
  { key: "pantai", label: "Pantai" },
  { key: "gunung", label: "Gunung" },
  { key: "budaya", label: "Budaya" },
];
